#define LBRACE                           1
#define RBRACE                           2
#define COMMA                            3
#define IDENTIFIER                       4
#define COLON                            5
#define JNULL                            6
#define BOOLEAN                          7
#define NUMBER                           8
#define STRING                           9
#define LBRACKET                        10
#define RBRACKET                        11
